### ISSUE TITLE
appsody build is not working

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/customer-ms-spring#7]
Though the couchdb container is up and running, `appsody build` does not work

**Comment by oiricaud** [comment]
Hey not sure what you mean appsody build is not working can you share your output?
This is what I got
<img width="1024" alt="Screen Shot 2020-05-21 at 7 48 51 AM" src="https://user-images.githubusercontent.com/11867058/82560680-854acd80-9b37-11ea-95af-91cee838a391.png">
