### ISSUE TITLE
appsody deploy is not working

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/customer-ms-spring#8]
If the test class is enabled `appsody deploy fails`

**Comment by oiricaud** [comment]
``` xml
<properties>
    <java.version>1.8</java.version>
    <spring-cloud.version>Greenwich.SR5</spring-cloud.version>
    <maven.test.skip>true</maven.test.skip>
  </properties>
```

Enabled because the test cases I wrote are independent of the spring boot application. Will resolve this later by mocking the controller class or removing the test cases.
